config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  #USER ROUTES
  resources :user
  get "register", to: "user#new", :as => "register"
  post "register", to: "user#create"

  #DASHBOARD ROUTES
  resources :dashboard

  #CONVERSATION ROUTES
  resources :conversation

  #CONTACT ROUTES
  resources :contact
  get "search", to: "contact#search"
  post "search", to: "contact#search"

  #MESSAGE ROUTES
  resources :message

  #STATUS ROUTES
  resources :status

  #SESSION ROUTES
  resources :session
  get "login", to: "session#index", :as => "login"
  post "login", to: "session#create"
  get "logout", to: "session#destroy", :as => "logout"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action -> { check_session(true,false) }

	def index
		@conversations = []
		Contact.where("user_one_id = ? OR user_two_id = ?",@current_user.id,@current_user.id).each do |contact|
			@conversations << contact.conversation if contact.conversation != nil
		end
	end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1>Chats</h1>
<p>
	<%= link_to "Neuer Chat", new_conversation_path %>
</p>
<ul id="chat_list">
	<% @conversations.each do |conversation| %>
	<li>
		<a href="/conversation/<%= conversation.id %>" class="conversation_preview_box">
			<% if conversation.contact.user_one_id == @current_user.id %>
				<h3><%= conversation.contact.user_two.nick_name %></h3>
			<% else %>
				<h3><%= conversation.contact.user_one.nick_name %></h3>
			<% end %>
			<p>
				<span class="last_chat_time"><%= "(" + time_ago_in_words(conversation.messages.last.updated_at) + ")" %></span>
				<span class="last_chat_message"><%= conversation.messages.last.content %></span>
				<%= "(" + conversation.messages.where("read = 'f' AND user_id != ?", @current_user.id).count.to_s + ")" if conversation.messages.where("read = 'f' AND user_id != ?", @current_user.id).count > 0 %>
			</p>
		</a>
	</li>
	<% end %>
</ul>