config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  #USER ROUTES
  resources :user
  get "register", to: "user#new", :as => "register"
  post "register", to: "user#create"

  #DASHBOARD ROUTES
  resources :dashboard

  #CONVERSATION ROUTES
  resources :conversation

  #CONTACT ROUTES
  resources :contact
  get "search", to: "contact#search"
  post "search", to: "contact#search"

  #MESSAGE ROUTES
  resources :message

  #STATUS ROUTES
  resources :status

  #SESSION ROUTES
  resources :session
  get "login", to: "session#index", :as => "login"
  post "login", to: "session#create"
  get "logout", to: "session#destroy", :as => "logout"

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	before_action -> { check_session(false,false) }

	def index
		redirect_to dashboard_index_path if @current_user 
	end

	def create
		if !params[:mail_address].blank? && !params[:password].blank?
			user = User.authenticate(params[:mail_address],params[:password])
			if user
				cookies.signed[:user_id] = user.id
				redirect_to dashboard_index_path
			else
				redirect_to login_path
			end
		else
			redirect_to login_path
		end
	end

	def destroy
		cookies.signed[:user_id] = nil
		redirect_to login_path
	end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/index.html.erb
<h1>Login</h1>
<%= form_tag login_path, method: :post do %>
	<%= label_tag "mail_address", "Mailadresse" %><br />
	<%= text_field_tag "mail_address" %><br /><br />
	<%= label_tag "password", "Passwort" %><br />
	<%= password_field_tag "password" %><br /><br />
	<%= submit_tag "Login" %>
<% end %>
<p>
	<%= link_to "Registrieren", register_path %>
</p>