config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  #USER ROUTES
  resources :user
  get "register", to: "user#new", :as => "register"
  post "register", to: "user#create"

  #DASHBOARD ROUTES
  resources :dashboard

  #CONVERSATION ROUTES
  resources :conversation

  #CONTACT ROUTES
  resources :contact
  get "search", to: "contact#search"
  post "search", to: "contact#search"

  #MESSAGE ROUTES
  resources :message

  #STATUS ROUTES
  resources :status

  #SESSION ROUTES
  resources :session
  get "login", to: "session#index", :as => "login"
  post "login", to: "session#create"
  get "logout", to: "session#destroy", :as => "logout"

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

	has_many :messages
	belongs_to :contact, class_name: "Contact", foreign_key: "contact_id"

	validates :contact_id, :presence => true

end

app/controllers/conversation_controller.rb
class ConversationController < ApplicationController

	before_action -> { check_session(true,false) }

	def index
		redirect_to dashboard_index_path
	end

	def show
		if Conversation.find_by_id params[:id]
			@conversation = Conversation.find_by_id params[:id]
			@messages = Message.where(:conversation_id => @conversation.id).order(:created_at)
			if @conversation.contact.user_one_id == @current_user.id
	    		@partner_id = @conversation.contact.user_two_id
			else
				@partner_id = @conversation.contact.user_one_id
			end
			if Contact.where("user_one_id = ? AND user_two_id = ?", @current_user.id, @partner_id).count > 0
				@contact_id = Contact.where("user_one_id = ? AND user_two_id = ?", @current_user.id, @partner_id).first.id
			else
				@contact_id = Contact.where("user_one_id = ? AND user_two_id = ?", @partner_id, @current_user.id).first.id
			end
			@messages.where(:user_id => @partner_id, :read => false).each do |message|
				message.update_attributes :read => true
			end
		else
			redirect_to dashboard_index_path
		end
	end

	def new 
		
	end

	def create
		if !params[:partner_id].blank? && !params[:content].blank?
			if params[:partner_id].to_i != @current_user.id
				if Contact.where(:user_one_id => @current_user.id, :user_two_id => params[:partner_id].to_i).count > 0 || Contact.where(:user_two_id => @current_user.id, :user_one_id => params[:partner_id].to_i).count > 0
					if Contact.where(:user_one_id => @current_user.id, :user_two_id => params[:partner_id].to_i).first.conversation || Contact.where(:user_two_id => @current_user.id, :user_one_id => params[:partner_id].to_i).first.conversation
						if Contact.where(:user_one_id => @current_user.id, :user_two_id => params[:partner_id].to_i).first.conversation
							conversation = Contact.where(:user_one_id => @current_user.id, :user_two_id => params[:partner_id].to_i).first.conversation
						else
							conversation = Contact.where(:user_two_id => @current_user.id, :user_one_id => params[:partner_id].to_i).first.conversation
						end
						Message.create :content => params[:content], :conversation_id => conversation.id, :user_id => @current_user.id
						redirect_to conversation_path conversation.id
					else
						contact = Contact.create :user_one_id => @current_user.id, :user_two_id => params[:partner_id].to_i
						conversation = Conversation.create :contact_id => contact.id
						Message.create :content => params[:content], :conversation_id => conversation.id, :user_id => @current_user.id
						redirect_to conversation_path conversation.id
					end
				else
					contact = Contact.create :user_one_id => @current_user.id, :user_two_id => params[:partner_id].to_i
					conversation = Conversation.create :contact_id => contact.id
					Message.create :content => params[:content], :conversation_id => conversation.id, :user_id => @current_user.id
					redirect_to conversation_path conversation.id
				end
			else
				redirect_to dashboard_index_path
			end
		else
			redirect_to dashboard_index_path
		end
	end

end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/views/conversation/new.html.erb
<h1>Neuer Chat</h1>
<%= form_tag conversation_index_path, method: :post do %>
	<%= hidden_field_tag "user_id", @current_user.id %>
	<%= label_tag "partner_id", "Kontakt" %>
	<%= select_tag "partner_id", options_from_collection_for_select(User.all.order(:nick_name), "id", "nick_name"), prompt: "Bitte auswählen" %><br /><br />
	<%= label_tag "content", "Nachricht" %><br />
	<%= text_field_tag "content" %><br /><br />
	<%= submit_tag "Senden" %>
<% end %>

app/views/conversation/show.html.erb
<h1><%= link_to User.find_by_id(@partner_id).nick_name, contact_path(@contact_id)  %></h1>
<div id="in_conversation_messages_wrapper">
	<% @messages.each do |message| %>
		<% message.user_id == @current_user.id ? message_class = "my_message" : message_class = "partners_message" %>
		<p class=<%= message_class %>>
			<%= message.content %><br />
			<span class="meta_data_of_message">
				<%= message.updated_at.strftime("%H:%M") %>
				<%= message.read ? "(gelesen)" : "(ungelesen)" if message.user_id == @current_user.id %>
			</span>
		</p>
	<% end %>
</div>
<div id="new_message_form_wrapper">
	<%= form_tag message_index_path, method: :post do %>
		<%= hidden_field_tag "user_id", @current_user.id %>
		<%= hidden_field_tag "conversation_id", @conversation.id %>
		<%= text_area_tag "content" %>
		<%= submit_tag "Senden" %>
	<% end %>
</div>