config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  #USER ROUTES
  resources :user
  get "register", to: "user#new", :as => "register"
  post "register", to: "user#create"

  #DASHBOARD ROUTES
  resources :dashboard

  #CONVERSATION ROUTES
  resources :conversation

  #CONTACT ROUTES
  resources :contact
  get "search", to: "contact#search"
  post "search", to: "contact#search"

  #MESSAGE ROUTES
  resources :message

  #STATUS ROUTES
  resources :status

  #SESSION ROUTES
  resources :session
  get "login", to: "session#index", :as => "login"
  post "login", to: "session#create"
  get "logout", to: "session#destroy", :as => "logout"

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	belongs_to :user_one, class_name: "User", foreign_key: "user_one_id"
	belongs_to :user_two, class_name: "User", foreign_key: "user_two_id"
	has_one :conversation

	validates :user_one_id, :presence => true
	validates :user_two_id, :presence => true

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	before_action -> { check_session(true,false) }

	def index
		@contacts = Contact.where("user_one_id = ? OR user_two_id = ?",@current_user.id,@current_user.id)
	end

	def show
		if params[:id]
			if Contact.find_by_id params[:id]
				@contact = Contact.find_by_id params[:id]
				if @contact.user_one_id == @current_user.id || @contact.user_two_id == @current_user.id
					if @contact.user_one_id != @current_user.id
						@user = @contact.user_one
					else
						@user = @contact.user_two
					end
				else
					redirect_to contact_index_path
				end
			else
				redirect_to contact_index_path
			end
		else
			redirect_to contact_index_path
		end
	end

	def search
		if params[:search_method]
			if !params[:search_method].blank? && !params[:search_input].blank?
				if params[:search_method] == "mail_address"
					@search_output = User.find_by_mail_address params[:search_input] if User.find_by_mail_address params[:search_input]
				else
					@search_output = User.find_by_nick_name params[:search_input] if User.find_by_nick_name params[:search_input]
				end
			end
		end
	end

	def create 
		if !params[:contact_id].blank?
			if User.find_by_id params[:contact_id].to_i
				if Contact.where(:user_one_id => @current_user, :user_two_id => params[:contact_id].to_i).count == 0 && Contact.where(:user_two_id => @current_user, :user_one_id => params[:contact_id].to_i).count == 0
					Contact.create :user_one_id => @current_user.id, :user_two_id => params[:contact_id].to_i
				end
			end
		end
		redirect_to contact_index_path
	end

	def destroy
		if params[:id]
			if Contact.find_by_id params[:id]
				if Contact.find_by_id(params[:id]).user_one_id == @current_user.id || Contact.find_by_id(params[:id]).user_two_id
					Contact.find_by_id(params[:id]).destroy
				end
			end
		end
		redirect_to contact_index_path
	end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/index.html.erb
<h1>Kontaktliste</h1>
<p>
	<%= link_to "Kontaktsuche", search_path %>
</p>
<p>
	<ul id="my_contact_list">
		<% @contacts.each do |contact| %>
			<li>
				<% if contact.user_one.id != @current_user.id %>
					<%= link_to contact.user_one.nick_name, contact_path(contact.id)  %>
				<% else %>
					<%= link_to contact.user_two.nick_name, contact_path(contact.id) %>
				<% end %>
			</li>
		<% end %>
	</ul>
</p>

app/views/contact/search.html.erb
<h1>Kontaktsuche</h1>
<%= form_tag search_path, method: :post do %>
	<%= label_tag "search_method", "Suchen nach" %>
	<select name="search_method">
		<option value="mail_address">E-Mail</option>
		<option value="nick_name">Nickname</option>
	</select>
	<br /><br />
	<%= label_tag "search_input", "Sucheingabe" %><br />
	<%= text_field_tag "search_input" %><br /><br />
	<%= submit_tag "Suchen" %>
<% end %>
<p>
	<% if @search_output %>
		Gefundener Nutzer: <br />
		<%= @search_output.nick_name + " (" + @search_output.mail_address + ")" %> 
		<%= form_tag contact_index_path, method: :post do %>
			<%= hidden_field_tag "contact_id", @search_output.id %>
			<%= submit_tag "Kontakt hinzufügen" %>
		<% end %>
	<% else %>
		<% if params[:search_method] %>
			Keinen Nutzer, der den Angaben entspricht, gefunden!
		<% end %>
	<% end %>
</p>

app/views/contact/show.html.erb
<h1><%= @user.nick_name %></h1>
<p>
	E-Mail: <%= @user.mail_address %><br />
	Hinzugefügt am: <%= @contact.created_at.strftime("%d.%m.%Y") %><br />
	Gemeinsame Konversation: <%= @contact.conversation ? "Ja" : "Nein" %><br />
	Ausgetauschte Nachrichten: <%= @contact.conversation.messages.count.to_s if @contact.conversation %> <%= "keine" if !@contact.conversation %>
</p>
<p>
	Status: <%= @user.status.content %>
</p>
<p>
	<%= link_to "Zur Konversation", conversation_path(@contact.conversation.id) if @contact.conversation %>
</p>
<p>
	<%= link_to "Kontakt löschen", contact_path(@contact.id), method: :delete, data: { confirm: "Wirklich löschen?" }, :class => "contact_delete_link" %>
</p>